create table comments
(
    id       BIGINT primary key generated BY DEFAULT AS IDENTITY,
    comment  varchar(500),
    date     timestamp default CURRENT_TIMESTAMP,
    news_id  uuid not null,
    users_id uuid not null,
    foreign key (news_id) references news (id),
    foreign key (users_id) references users (id)
);